arenas:
  arena1:
    world: world
    start:
      x: 100
      y: 64
      z: 100
    finish:
      x: 150
      y: 64
      z: 150
    max_players: 4
  arena2:
    world: world
    start:
      x: 200
      y: 64
      z: 200
    finish:
      x: 250
      y: 64
      z: 250
    max_players: 4

reward_money: 500  # Hadiah uang untuk pemenang
